language: python
matrix:
  include:
    - python: 3.6
      env: TOXENV=py36
    - python: 3.5
      env: TOXENV=py35
    - python: 3.4
      env: TOXENV=py34
# before_install:
#   - sudo apt-get install packageA
#   - pip install packageB
install:
  - pip install tox
script:
  - tox

# safelist
branches:
  only:
  - master
  - develop

deploy:
  provider: pypi
  user: $TEST_PYPI_USER
  password: $TEST_PYPI_PASS
  server: https://test.pypi.org/legacy/
  distributions: "sdist bdist_wheel"
  on:
    branch: master
    condition: $TRAVIS_PYTHON_VERSION = "3.6"